### ISSUE TITLE
Website says GPLv3, license file says MIT

### ISSUE THREAD

**Issue by sir-ragna** [WimObiwan/FxGqlC#47]
The [websites](https://sites.google.com/site/fxgqlc/) mentions that this project falls under the GPLv3 while the license file actually says this project falls under the MIT license.
- Website says GPLv3: https://sites.google.com/site/fxgqlc/
- Github says MIT: https://github.com/WimObiwan/FxGqlC/blob/master/LICENSE

Funnily enough _SharpZipLib_, one of your dependencies has the exact same issue. 
- Website GPLv? https://icsharpcode.github.io/SharpZipLib/
- Github MIT? https://github.com/icsharpcode/SharpZipLib/blob/master/LICENSE.txt

My guess is that the documentation website requires an update.

**Comment by WimObiwan** [comment]
Indeed.  Should be GPLv3
Fixed by 7a89f37cf018a002285c12e87909245ed00adfb8
